### ISSUE TITLE
Move installation from Dockerfile to forest

### ISSUE THREAD

**Issue by JakobThumm** [JakobThumm/TUM-CONCERT-Docker#1]
Currently, many installation procedures are defined in the `Dockerfile`, such as installing `sara-shield`. 
We would like to define those in the [forest recipe](https://github.com/manuelvogel12/multidof_recipes] instead, as we then can also easily use these forest files to install everything locally during the next integration meeting.

**Comment by manuelvogel12** [comment]
This was done by https://github.com/JakobThumm/TUM-CONCERT-Docker/pull/4
